### ISSUE TITLE
Regarding Health Data Client Library

### ISSUE THREAD

**Issue by girikumarbathala** [jbharatrhodes/stepcounter#1]
Hello @jbharatrhodes,

The app you are building is for Smartphone or SmartWatch?

Can "com.google.android.libraries.healthdata:health-data-api:1.0.0-alpha01" library be used in Smartphone applications to extract health data from health apps like Google fit or Samsung Health?

Thank you.

**Comment by jbharatrhodes** [comment]
Hi
It is for smartwatch and I am struggling to include the background service, so that it runs continuously

**Comment by girikumarbathala** [comment]
Hi @jbharatrhodes 

Appreciate your prompt response.

Could you please confirm if "com.google.android.libraries.healthdata:health-data-api:1.0.0-alpha01" library be used in Smartphone applications to extract health data from health apps like Google fit or Samsung Health?

**Comment by jbharatrhodes** [comment]
I tried to use different approaches. If you use  "com.google.android.libraries.health data:health-data-api:1.0.0-alpha01", you can get data from google fit but you have to go through some authentication process and the token lasts for short time.

**Comment by girikumarbathala** [comment]
Thank you @jbharatrhodes
